"""empty message

Revision ID: b1ec63b3a03e
Revises: fdaf3972af13
Create Date: 2019-04-07 16:47:50.261730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ec63b3a03e'
down_revision = 'fdaf3972af13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_data', sa.Column('email_sent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_data', 'email_sent')
    # ### end Alembic commands ###
