"""empty message

Revision ID: e0ae7f77c0ba
Revises: 
Create Date: 2019-04-06 16:11:05.215462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ae7f77c0ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('from_email', sa.String(), nullable=True),
    sa.Column('to_email', sa.String(), nullable=True),
    sa.Column('email_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    # ### end Alembic commands ###
