"""empty message

Revision ID: fdaf3972af13
Revises: 
Create Date: 2019-04-07 10:43:51.926320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdaf3972af13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('from_email', sa.String(), nullable=True),
    sa.Column('to_email', sa.String(), nullable=True),
    sa.Column('email_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_data')
    # ### end Alembic commands ###
